// <auto-generated />
using LoyaltySystemAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltySystemAPI.Migrations
{
    [DbContext(typeof(LoyaltyContext))]
    partial class LoyaltyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyaltySystemAPI.Models.Loyalty", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Loyalty", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = "1",
                            Category = "zilver",
                            Points = "100"
                        },
                        new
                        {
                            CustomerID = "2",
                            Category = "zilver",
                            Points = "200"
                        },
                        new
                        {
                            CustomerID = "3",
                            Category = "platina",
                            Points = "2000"
                        },
                        new
                        {
                            CustomerID = "4",
                            Category = "goud",
                            Points = "600"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
