apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/sda1/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: pitstop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000

---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: pitstop
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000