# InfluxDB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:latest
          ports:
            - containerPort: 8086
            - containerPort: 8089

---
# InfluxDB Service
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: pitstop
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
    - protocol: TCP
      port: 8089
      targetPort: 8089
