apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: kubernetes
spec: 
  rules:
  - host: dashboard.com
    http:
      paths:
       - backend: 
          serviceName: kubernetes
          servicePort: 443