apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pitstop
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']

      - job_name: 'node'
        static_configs:
          - targets: ['node:9100']

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    version: v1
  name: prometheus
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: pitstop
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus