<<<<<<< HEAD
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: prometheus-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: standard
#   hostPath:
#     path: /mnt/sda1/data/prometheus

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prometheus-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard

# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
# data:
#   prometheus.yml: |
#     global:
#     scrape_interval: 1m
#     scrape_configs:
#     - job_name: 'prometheus'
#     scrape_interval: 1m
#     static_configs:
#     - targets: ['prometheus:9090']

#     - job_name: 'node'
#     scrape_interval: 1m
#     static_configs:
#     - targets: ['node:9100']
=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pitstop
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']

      - job_name: 'node'
        static_configs:
          - targets: ['node:9100']
>>>>>>> fc582d1a7ec1146d38405a81519fdbd8f0ce530a

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: pitstop
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus