apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: logserver
  name: logserver
spec:
  ports:
    - name: "5341"
      port: 5341
      targetPort: 80
  selector:
    io.kompose.service: logserver
status:
  loadBalancer: {}
