apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mailserver
  name: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: mailserver
    spec:
      containers:
        - image: maildev/maildev:1.1.0
          name: mailserver
          ports:
            - containerPort: 25
              hostPort: 25
              protocol: TCP
            - containerPort: 80
              hostPort: 4000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
