apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: sqlserver
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: 8jkGh47hnDw89Haq8LN2
          image: mcr.microsoft.com/azure-sql-edge
          name: sqlserver
          ports:
            - containerPort: 1433
              hostPort: 1434
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserverdata
      restartPolicy: Always
      volumes:
        - name: sqlserverdata
          persistentVolumeClaim:
            claimName: sqlserverdata
status: {}
