apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: workshopmanagementapi
  name: workshopmanagementapi
spec:
  ports:
    - name: "5200"
      port: 5200
      targetPort: 5200
  selector:
    io.kompose.service: workshopmanagementapi
status:
  loadBalancer: {}
