{
 "title": "Loyalty dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Aantal klanten",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "CustomerManagement",
     "rawSql": "SELECT COUNT(DISTINCT CustomerID) AS total_customers FROM Loyalty\r\n"
    }
   ]
  },
  {
   "title": "Gemiddeld aantal punten per klant",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "CustomerManagement",
     "rawSql": "SELECT AVG(CAST(Points AS int)) as avg_points FROM Loyalty\r\n"
    }
   ]
  },
  {
   "title": "Punten verdeling",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Loyalty",
     "rawSql": "SELECT Category, COUNT(*) as count FROM Loyalty GROUP BY Category"
    }
   ]
  },
  {
   "title": "Totaal aantal punten",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "CustomerManagement",
     "rawSql": "SELECT SUM(CAST(Points AS int)) as total_points FROM Loyalty\r\n"
    }
   ]
  }
 ]
}