name: Build and Test .NET Project
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
    
    - name: cache
      uses: actions/cache@v3
      with:
        key: loyaltysystemapi
        path: ./src
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: cache
      uses: actions/cache@v3
      with:
        key: loyaltysystemapi
        path: ./src

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - run: cat src/VehicleManagementAPI/Dockerfile
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src/LoyaltySystemAPI
        push: true
        tags: ghcr.io/hanaim-devops/loyaltysystemapi:1.0
        file: ./src/LoyaltySystemAPI/Dockerfile
