name: Build and Test .NET Project
on:
  push:
    branches: [ "main", "feature/actions-docker-registry" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build
      run: |
        cd ./src/LoyalitySystemAPI
        dotnet restore
        dotnet publish -c release -o ./../app --no-restore
 
    - name: Release 
      # env:
      #   DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        cd ./src/LoyalitySystemAPI
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build -t loyaltysystemapi .
        docker tag loyaltysystemapi $DOCKER_USER/loyaltysystemapi:1.1
        docker push $DOCKER_USER/loyaltysystemapi:1.1