name: Build and Test .NET Project
on:
  push:
    branches: [ "main", "feature/actions-docker-registry" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build
      run: |
        cd ./src/LoyalitySystemAPI
        dotnet restore
        dotnet publish -c release -o ./../app --no-restore
 
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Login docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/loyaltysystemapi:1.0
