name: Build and Test .NET Project
on:
  push:
    branches: [ "main", "feature/actions-docker-registry" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: feature/actions-docker-registry
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build
      run: |
        cd ./src
        dotnet restore
        dotnet publish -c release -o ./app --no-restore
    
    - name: cache
      uses: actions/cache@v3
      with:
        key: loyaltysystemapi
        path: ./src
 
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: cache
      uses: actions/cache@v3
      with:
        key: loyaltysystemapi
        path: ./src

    - name: Login docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - run: cat src/VehicleManagementAPI/Dockerfile

    - run: git branch

    - name: Set up Docker Compose
      run: docker-compose -f src/docker-compose.yml build --no-cache
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src
        push: true
        tags: hanaim-devops/loyaltysystemapi:1.0
