name: Execute Shell Script on Main Push

on:
  push:
    branches:
      - main

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute shell script
        run: |
          chmod +x src/k8s/start-all-cluster.sh
          ./src/k8s/start-all-cluster.sh
