apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-docker-image
spec:
  description: Build the separate docker image then push to Docker registry.
  params:
    - name: image-name-tag
      type: string
  workspaces:
  - name: source
  steps:
  - name: build
    image: gcr.io/kaniko-project/executor:latest
    command:
    - /kaniko/executor
    args:
      - --context
      - $(workspaces.source.path)
      - --dockerfile
      - $(workspaces.source.path)/src/LoyaltySystemAPI/Dockerfile
      - --destination
      - docker.io/kafune/loyaltysystemapi:1.0

    # docker build -t $(params.image-name-tag) .
    # docker push $(params.image-name-tag)