apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-role-binding
subjects:
- kind: ServiceAccount
  name: git-docker-service-account
roleRef:
  kind: Role
  name: kaniko-role
  apiGroup: rbac.authorization.k8s.io