apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-image-task-run-
spec:
  serviceAccountName: git-docker-service-account
  taskRef:
    name: deploy-image-task
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  # - name: git-secret
  #   secret:
  #     secretName: git-secret
  # - name: docker-credentials
  #   secret:
  #     secretName: docker-credentials
  params:
  - name: repo-url
    value:
  - name: image-reference
    value:
  - name: image-name-tag
    value: